### ISSUE TITLE
how can I make it voice command in this plugin?

### ISSUE THREAD

**Issue by shioshikei** [daao87/ContinuousSpeechRecognizer#3]
so I wanna use the speech recognition as voice command, if user said "A" it will have some function. are that possible?

**Comment by dalvallana** [comment]
Yes. You'd just have to ask in your javascript code if what the recognizer detected, and if it was "A", or "B", or "C", call the proper function accordingly.

**Comment by shioshikei** [comment]
and yeah i was ask what code for detected the word, can you give an example? thanks a lot

**Comment by dalvallana** [comment]
In the readme file of this repository you can find an example. Particularly, you're interested in:

`window.continuoussr.startRecognize(function(result){
                    alert(result);
                }`

In that callback function you can ask for whatever you want to detect.

**Comment by shioshikei** [comment]
sorry I still confused, so what I must declare to catch the word that I want use as command?

**Comment by dalvallana** [comment]
Don't worry. Please refer to the example in the readme and you'lll get to it.
